{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "grace.serviceAccountName" . }}
  labels:
{{ include "grace.labels" . | indent 4 }}
{{- end -}}
